name: BackenD
on:
  push:
    branches: [ main ]
    paths:
      - '**/*.java'
      - './'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.java'
      - 'backend/propmanage/pom.xml'
      - '.github/workflows/backend.yml'
  workflow_dispatch: # Adicionado para permitir execução manual

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '17' ]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      
      - name: Build Java project
        run: mvn clean package --file backend/propmanage/pom.xml
      
      - name: Test Java project
        run: mvn test --file backend/propmanage/pom.xml
